/*
 * File: xds_index.js
 * Date: Wed Sep 22 2010 11:16:57 GMT-0700 (PDT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new CarbonImpactGrid({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
